/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:57b19058-9563-4d6d-9f1c-17922224b62f",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_JfAcaDP8f",
    "aws_user_pools_web_client_id": "70ukb17v9a08hvb6vpvqqcdbfr",
    "oauth": {}
};


export default awsmobile;
